# Generated by Django 3.2.5 on 2022-02-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=8, verbose_name='用户名')),
                ('gender', models.CharField(max_length=1, verbose_name='性别')),
            ],
        ),
    ]
